# Generated by Django 5.1.3 on 2025-02-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('pointsFidelite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('moyenPaiement', models.CharField(choices=[('TMoney', 'TMoney'), ('Flooz', 'Flooz')], max_length=10)),
                ('statut', models.CharField(choices=[('Validé', 'Validé'), ('Échoué', 'Échoué')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Vendeur', 'Vendeur')], max_length=10)),
                ('motDePasse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='ShopEaseApp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('alerteStock', models.BooleanField(default=False)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ShopEaseApp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='TableauDeBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventesJour', models.IntegerField()),
                ('ventesMois', models.IntegerField()),
                ('articlesRuptureStock', models.ManyToManyField(to='ShopEaseApp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montantTotal', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopEaseApp.client')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShopEaseApp.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='RetourRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRetour', models.DateTimeField()),
                ('raison', models.TextField()),
                ('statut', models.CharField(choices=[('Accepté', 'Accepté'), ('Refusé', 'Refusé')], max_length=10)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopEaseApp.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmission', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField()),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShopEaseApp.vente')),
            ],
        ),
    ]
